#!/bin/sh

# Runs Prettier, ESLint and tsc on .ts, .tsx, .js, .md, .css and .json files. Prettier and ESLint only check the
# committed files, whereas tsc checks all project files, since it's not possible to run tsc on specific files while
# obeying the tsconfig.json options (see https://github.com/microsoft/TypeScript/issues/27379 and
# https://www.npmjs.com/package/tsc-files).
# This hook always commits, even if errors are found. And it does not modify the files (ie it does not do `prettier
# write`), it only checks if there is any issue and reports it.
# Inspired by https://prettier.io/docs/en/precommit.html#option-6-shell-script

get_staged_files() {
  ALL_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | awk '/\.ts$|\.tsx$|\.js$|\.md|\.css|\.json/')
  ALL_CODE_FILES=$(echo "$ALL_FILES" | awk '/\.ts$|\.tsx$|\.js$/')
  FILES_SERVER=$(echo "$ALL_CODE_FILES" | awk '/server\//' | sed 's/server\///')
  FILES_WEB=$(echo "$ALL_CODE_FILES" | awk '/web\//' | sed 's/web\///')
}

print_title() {
  printf "\n\n🔍 %s\n\n" "$1"
}

print_result() {
  ERROR_CODE=$?
  if [ $ERROR_CODE -eq 0 ]; then
    printf "\n✅ %s Success\n\n" "$1"
  else
    printf "\n❌ %s Failure\n\n" "$1"
  fi
}

get_staged_files

# Prettier on both server and web

printf "📁 Files\n\n%s" "$ALL_FILES"
[ -z "$ALL_FILES" ] && exit 0

print_title "Prettier"
echo "$ALL_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --check
print_result "Prettier"

# ESLint and tsc on server

cd server || exit 1

printf "📁 Files server\n\n%s" "$FILES_SERVER"

print_title "ESLint server"
echo "$FILES_SERVER" | xargs ./node_modules/.bin/eslint
print_result "ESLint server"

print_title "tsc server"
npx tsc --noEmit
print_result "tsc server"

# ESLint and tsc on web

cd ..
cd web || exit 1

printf "📁 Files web\n\n%s" "$FILES_WEB"
[ -z "$FILES_WEB" ] && exit 0

print_title "ESLint web"
echo "$FILES_WEB" | xargs ./node_modules/.bin/eslint
print_result "ESLint web"

print_title "tsc web"
npx tsc --noEmit
print_result "tsc web"

cd ..

exit 0
