apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: recipe-manager
  labels:
    app: recipe-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: REPLACE_WITH_AWS_REGION
