apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - external-secret.yaml

# Labels for all resources
labels:
  - pairs:
      environment: dev

patches:
  - path: ingress_patch.yaml
  - path: configmap_patch.yaml
  - path: secret-store-patch.yaml

images:
  - name: recipe-manager-api
    newName: DEPLOY_TIME_ECR_REPOSITORY_URL
    newTag: DEPLOY_TIME_IMAGE_TAG
