apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recipe-manager

resources:
  - ../../base
  - external-secret.yaml

# Labels for all resources
labels:
  - pairs:
      environment: dev

patches:
  - path: ingress_patch.yaml
  - path: configmap_patch.yaml
images:
  - name: recipe-manager-api-server
    newName: 725270464668.dkr.ecr.us-east-1.amazonaws.com/recipe-manager-server-dev
    newTag: 32656f6
