# https://external-secrets.io/latest/provider/aws-secrets-manager/
# What data to fetch
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recipe-manager-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: recipe-manager-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: recipe-manager-rds-master-password-prod
    - secretKey: JWT_SECRET
      remoteRef:
        key: recipe-manager-jwt-secret-prod
    - secretKey: EMAIL_USER
      remoteRef:
        key: recipe-manager-email-user-prod
    - secretKey: EMAIL_PASSWORD
      remoteRef:
        key: recipe-manager-email-password-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recipe-manager-api-parameters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: recipe-manager-api-parameters
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /recipe-manager/prod/rds-address
